InAndOut/Models/ErrorViewModel.cs
using System;

namespace InAndOut.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InAndOut/Models/ExpenseType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Models
{
    public class ExpenseType
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

    }
}

InAndOut/Models/Expenses.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Models
{
    public class Expense
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Expense")]
        public string ExpenseName { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage ="Amount must be greater than 0")]
        public int Amount { get; set; }
        [DisplayName("Expense Type")]
        public int ExpenseTypeId { get; set; }
        [ForeignKey("ExpenseTypeId")]
        public virtual ExpenseType ExpenseType { get; set; }

    }
}

InAndOut/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }
        public string Borrower { get; set; }
        public string Lender{ get; set; }
        [DisplayName("Item Name")]
        public string ItemName { get; set; }



    }
}

InAndOut/Models/ViewModels/ExpenseVm.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Models.ViewModels
{
    public class ExpenseVm
    {
        public Expense Expense { get; set; }
        public IEnumerable<SelectListItem> TypeDropDown { get; set; }
    }
}

InAndOut/Controllers/AppoinmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class AppoinmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

InAndOut/Controllers/ExpensesController.cs
using InAndOut.Data;
using InAndOut.Models;
using InAndOut.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ExpensesController(ApplicationDbContext context)
        {
            _context = context;
        }
        // Get List
        public IActionResult Index()
        {
            IEnumerable<Expense> list = _context.Expenses;

            foreach(var model in list)
            {
                model.ExpenseType = _context.ExpenseTypes
                    .FirstOrDefault(x => x.Id == model.ExpenseTypeId);
            }
            return View(list);
        }

        // Get Create
        [HttpGet]
        public IActionResult Create()
        {
            //IEnumerable<SelectListItem> TypeDropDown =
            //   _context.ExpenseTypes.Select(x => new SelectListItem
            //   {
            //       Text = x.Name,
            //       Value = x.Id.ToString()
            //   });

            //ViewBag.TypeDropDown = TypeDropDown;
            ExpenseVm expenseVm = new ExpenseVm()
            {
                Expense = new Expense(),
                TypeDropDown = _context.ExpenseTypes
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
            };
            return View(expenseVm);
        }

        // Post Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ExpenseVm expenses)
        {
            if (ModelState.IsValid)
            {
                // expenses.ExpenseTypeId = 1;
                _context.Expenses.Add(expenses.Expense);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expenses);
        }

        // Get-Update
        [HttpGet]
        public IActionResult Update(int? id)
        {
            ExpenseVm expenseVm = new ExpenseVm()
            {
                Expense = new Expense(),
                TypeDropDown = _context.ExpenseTypes
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
            };
            if (id == null || id == 0)
            {
                return NotFound();
            }
            expenseVm.Expense = _context.Expenses.Find(id);
            if (expenseVm.Expense == null)
            {
                return NotFound();
            }
            return View(expenseVm);
        }

        // Post Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ExpenseVm model)
        {
            if (ModelState.IsValid)
            {
                _context.Expenses.Update(model.Expense);
                _context.SaveChanges();

                return RedirectToAction();
            }

            return View(model);
        }

        // Get Delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _context.Expenses.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        // Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost (int? id)
        {
            var exp = _context.Expenses.Find(id);
            if (exp == null)
            {
                return NotFound();
            }
            _context.Expenses.Remove(exp);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

InAndOut/Controllers/HomeController.cs
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InAndOut/Controllers/ItemController.cs
using InAndOut.Data;
using InAndOut.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InAndOut.Controllers
{
    public class ItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemController(ApplicationDbContext context)
        {
            _context = context;    
        }
        public IActionResult Index()
        {
            IEnumerable<Item> objList = _context.Items;
            return View(objList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Item obj)
        {
            _context.Items.Add(obj);
            _context.SaveChanges();

            return RedirectToAction("Index");
           
        }
    }
}

InAndOut/Views/Appoinment/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

InAndOut/Views/ExpenseType/Create.cshtml
@model ExpenseType

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add ExpenseType</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                   
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    
                </div>
                <div class="form-group row">
                    
                    <div class="col-4">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
 }

InAndOut/Views/ExpenseType/Delete.cshtml
@model InAndOut.Models.ExpenseType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense Type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                    
                </div>
                <div class="form-group row">
                    
                    <div class="col-6">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                    
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/Views/ExpenseType/Index.cshtml
@model IEnumerable<ExpenseType>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expenses List</h2>
        </div>
        <div class="col-6">
            <a asp-controller="ExpenseType" asp-action="Create" class="btn btn-primary">Create New Expenses</a>
        </div>
    </div>
    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Expense Type
                    </th>
                   
                    <th>
                        Changes
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var expens in Model)
                {
                    <tr>
                        <td width="35%">@expens.Id</td>
                        <td width="35%">@expens.Name</td>
                     
                        <td width="30%">
                            <div class="w-100 btn-group" role="group">
                                <a asp-controller="ExpenseType" asp-action="Update" asp-route-Id="@expens.Id" class="btn btn-primary mx-1">Update</a>
                                <a asp-controller="ExpenseType" asp-action="Delete" asp-route-Id="@expens.Id" class="btn btn-danger mx-1">Delete</a>
                            </div>
                        </td>
                        
                    </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <p>No Expenses Created yet</p>
    }
</div>

InAndOut/Views/ExpenseType/Update.cshtml
@model InAndOut.Models.ExpenseType

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Expense Type</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/Views/Expenses/Create.cshtml
@model InAndOut.Models.ViewModels.ExpenseVm

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Expense.ExpenseName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Expense.Amount"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Expense.ExpenseType"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Expense.ExpenseName" class="form-control" />
                        <span asp-validation-for="Expense.ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Expense.Amount" class="form-control" />
                        <span asp-validation-for="Expense.Amount" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <select asp-for="Expense.ExpenseTypeId" asp-items="@Model.TypeDropDown" class="form-control" >
                            <option selected>--Selected Expense Type--</option>
                        </select>
                        <span asp-validation-for="Expense.ExpenseTypeId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{ <partial name="_ValidationScriptsPartial" />}
 }

InAndOut/Views/Expenses/Delete.cshtml
@model InAndOut.Models.Expense

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    
                    <div class="col-6">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Amount"></label>
                    </div>

                </div>
                <div class="form-group row">
                    
                    <div class="col-6">
                        <input asp-for="ExpenseName" disabled class="form-control" />
                    </div>
                    <div class="col-6">
                        <input asp-for="Amount" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/Views/Expenses/Index.cshtml
@model IEnumerable<InAndOut.Models.Expense>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expenses List</h2>
        </div>
        <div class="col-6">
            <a asp-controller="Expenses" asp-action="Create" class="btn btn-primary">Create New Expenses</a>
        </div>
    </div>
    <br />
    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Id
                    </th>
                    <th>
                        Expenses Name
                    </th>
                    <th>
                        Amount
                    </th>
                    <th>
                        Expense Type
                    </th>
                    <th>
                        Changes
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var expens in Model)
                {  
                <tr>
                    <td width="25%">@expens.Id</td>
                    <td width="25%">@expens.ExpenseName</td>
                    <td width="25%">@expens.Amount</td>
                    <td width="25%">@expens.ExpenseType.Name</td>
                    <td width="25%">
                        <div class="w-100 btn-group" role="group">
                            <a asp-controller="Expenses" asp-action="Update" asp-route-Id="@expens.Id" class="btn btn-primary mx-1 ">Update</a>
                            <a asp-controller="Expenses" asp-action="Delete" asp-route-Id="@expens.Id" class="btn btn-danger mx-1">Delete</a>
                        </div>
                    </td>

                </tr>
                }
            </tbody>
        </table>

    }
    else
    {
        <p>No Expenses Created yet</p>
    }
</div>

InAndOut/Views/Expenses/Update.cshtml
@model InAndOut.Models.ViewModels.ExpenseVm

<form method="post">
    <input asp-for="Expense.Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Expense</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Expense.ExpenseName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Expense.Amount"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Expense.ExpenseType"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="Expense.ExpenseName" class="form-control" />
                        <span asp-validation-for="Expense.ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Expense.Amount" class="form-control" />
                        <span asp-validation-for="Expense.Amount" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <select asp-for="Expense.ExpenseTypeId" asp-items="@Model.TypeDropDown" class="form-control">
                            <option selected>--Selected Expense Type--</option>
                        </select>
                        <span asp-validation-for="Expense.ExpenseTypeId" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

InAndOut/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InAndOut/Views/Item/Create.cshtml
@model Item

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ItemName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Borrower"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Lender"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ItemName" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Borrower" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Lender" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

InAndOut/Views/Item/Index.cshtml
@model IEnumerable<Item>


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Items List</h2>
        </div>
        <div class="col-6">
            <a asp-controller="Item" asp-action="Create" class="btn btn-primary">Create New Item</a>
        </div>
    </div>
    <br />
    @if(Model.Count() > 0)
     {
         <table class="table table-bordered table-striped" style="width:100%">
             <thead>
                 <tr>
                     <th>
                         Id
                     </th>
                     <th>
                         Item Name
                     </th>
                     <th>
                         Borrower
                     </th>
                     <th>
                         Lender
                     </th>
                 </tr>
             </thead>
             <tbody>
                 @foreach(var item in Model)
                {
                 <tr>
                     <td width="30%">@item.Id</td>
                     <td width="30%">@item.Borrower</td>
                     <td width="30%">@item.ItemName</td>
                     <td width="30%">@item.Lender</td>
                 </tr>
                }
             </tbody>
         </table>   

    }
    else
    {
        <p>No Items Created yet</p>
    }
</div>

InAndOut/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InAndOut</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InAndOut</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">My Borrowed Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">My Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExpenseType" asp-action="Index">My Expense Type</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - InAndOut - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>